### ISSUE TITLE
Update heroku 

### ISSUE THREAD

**Issue by ahmedlhanafy** [ar-maged/guc-api#21]

**Comment by ar-maged** [comment]
The Heroku deployment is updated 13 hours ago. Check commits [9cae50b](https://github.com/ar-maged/guc-api/commit/9cae50b953be0fe67656e736054914e2e6f441b7) & [ed3a50f](https://github.com/ar-maged/guc-api/commit/ed3a50f7e059b604abdad6dc56177c21c1cb6016).

The deployment is currently supporting **both** `GET` & `POST` GraphQL requests.
