### ISSUE TITLE
Enable CORS for preflight requests

### ISSUE THREAD

**Issue by abdelrahman-elkady** [ar-maged/guc-api#25]
Consider enabling CORS by setting `Access-Control-Allow-Origin` header in the server response for the requesting origin, check the answer [here](http://stackoverflow.com/a/24818638/3357910) as an example

**Comment by ar-maged** [comment]
It's my first time getting introduced to CORS. Thanks for the heads-up!

Would [this](https://github.com/ar-maged/guc-api/commit/f42d9a0f9c05600a2d96793e40aa95972ec3fe66) be adequate enough?

**Comment by abdelrahman-elkady** [comment]
This is working now perfectly after merging #26, Thank you :))

**Comment by ar-maged** [comment]
Was just about to say it's fixed & the deployment is updated :smile:

You're welcome - thanks for the heads-up about CORS! :+1:
